// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzrmrXL3IBtFVrlcZLLZ_yKLLdT6r_PNk',
    appId: '1:885872350985:web:c537d018813d928e8865d8',
    messagingSenderId: '885872350985',
    projectId: 'flutter-jurnal',
    authDomain: 'flutter-jurnal.firebaseapp.com',
    storageBucket: 'flutter-jurnal.appspot.com',
    measurementId: 'G-Q93YHZR1GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlX9vqDH2KfFTH8JPR1d07If1CeD_ncJo',
    appId: '1:885872350985:android:ac9388281848fd3e8865d8',
    messagingSenderId: '885872350985',
    projectId: 'flutter-jurnal',
    storageBucket: 'flutter-jurnal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yU9o81p_PllCthQNm2s_Mh02BjlUUw4',
    appId: '1:885872350985:ios:0a624015b02bbf948865d8',
    messagingSenderId: '885872350985',
    projectId: 'flutter-jurnal',
    storageBucket: 'flutter-jurnal.appspot.com',
    iosClientId: '885872350985-tl2uaosel6ojouel3qlchdn6f1o3je4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.eJupeSkensa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7yU9o81p_PllCthQNm2s_Mh02BjlUUw4',
    appId: '1:885872350985:ios:37f2b2a97af6413f8865d8',
    messagingSenderId: '885872350985',
    projectId: 'flutter-jurnal',
    storageBucket: 'flutter-jurnal.appspot.com',
    iosClientId: '885872350985-nqac2gp8jekqdtjoq58a1kfg0hh7if80.apps.googleusercontent.com',
    iosBundleId: 'com.example.eJupeSkensa.RunnerTests',
  );
}
